apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - backend.yaml
  - ml-service.yaml
  - ingress.yaml

# These images will be dynamically replaced by kustomize during GitHub Actions CI
images:
  - name: backend-image
    newName: asia-south1-docker.pkg.dev/your-project-id/anti-ddos-repo/backend
    newTag: latest
  - name: ml-service-image
    newName: asia-south1-docker.pkg.dev/your-project-id/anti-ddos-repo/ml-service
    newTag: latest
  - name: frontend-image
    newName: asia-south1-docker.pkg.dev/your-project-id/anti-ddos-repo/frontend
    newTag: latest
